# Generated by Django 5.0.2 on 2024-02-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sap_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_term',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='inn',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='sap_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sap_id',
            field=models.IntegerField(unique=True),
        ),
    ]
