# Generated by Django 5.0.2 on 2024-02-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_company_inn_alter_company_sap_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
