# Generated by Django 5.0.2 on 2024-02-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_payment_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deliver_penalty_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='max_deliver_penalty_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='max_paid_penalty_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='paid_penalty_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_term',
            field=models.IntegerField(default=60, null=True),
        ),
    ]
