# Generated by Django 5.0.2 on 2024-02-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contract_deliver_penalty_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='remains_deliver_amount',
            field=models.FloatField(blank=True),
        ),
    ]
