# Generated by Django 5.0.2 on 2024-02-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_contract_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deliver',
            name='paid_fact',
            field=models.DateField(blank=True, null=True),
        ),
    ]
