# Generated by Django 5.0.2 on 2024-04-05 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_alter_contract_amount_alter_deliver_paid_fact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beforepretension',
            options={'ordering': ['note_date'], 'verbose_name': 'Допретензионное требование', 'verbose_name_plural': 'Допретензионные требования'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['cut_name'], 'verbose_name': 'Общество', 'verbose_name_plural': 'Общества'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['start_date', '-sum_of_pretensions'], 'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='deliver',
            options={'ordering': ['invoice_date', 'invoice'], 'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['cut'], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='lawsuit',
            options={'ordering': ['note_date'], 'verbose_name': 'Исковое требование', 'verbose_name_plural': 'Исковые требования'},
        ),
        migrations.AlterModelOptions(
            name='lawsuitnote',
            options={'ordering': ['note_date'], 'verbose_name': 'СЗ об инициировании исковой', 'verbose_name_plural': 'СЗ об инициировании исковой'},
        ),
        migrations.AlterModelOptions(
            name='pretension',
            options={'ordering': ['note_date'], 'verbose_name': 'Претензия', 'verbose_name_plural': 'Претензии'},
        ),
        migrations.AlterModelOptions(
            name='pretensionnote',
            options={'ordering': ['note_date'], 'verbose_name': 'СЗ об инициировании ПИР', 'verbose_name_plural': 'СЗ об инициировании ПИР'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['sap_code', '-total_penalty'], 'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['main_man', 'dep_director', 'sap_id'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='beforepretension',
            name='answer_image',
            field=models.FileField(blank=True, upload_to='beforepretension/answers/%Y/%m/%d/%s', verbose_name='Ответ (скан)'),
        ),
        migrations.AlterField(
            model_name='beforepretension',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='beforepretension',
            name='have_answer',
            field=models.BooleanField(default=False, verbose_name='Статус ответа'),
        ),
        migrations.AlterField(
            model_name='beforepretension',
            name='is_satisfied',
            field=models.BooleanField(default=False, verbose_name='Статус удовлетворения требований'),
        ),
        migrations.AlterField(
            model_name='beforepretension',
            name='letter_image',
            field=models.FileField(upload_to='beforepretension/%Y/%m/%d/%s', verbose_name='Письмо (скан)'),
        ),
        migrations.AlterField(
            model_name='beforepretension',
            name='note_date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='beforepretension',
            name='number',
            field=models.CharField(max_length=10, verbose_name='№ Допретензионного требования'),
        ),
        migrations.AlterField(
            model_name='beforepretension',
            name='penalty_amount',
            field=models.FloatField(verbose_name='Сумма требований'),
        ),
        migrations.AlterField(
            model_name='beforepretension',
            name='penalty_paid',
            field=models.FloatField(default=0, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cut_name',
            field=models.CharField(max_length=50, verbose_name='Сокращенное наименование'),
        ),
        migrations.AlterField(
            model_name='company',
            name='e_mail',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='company',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.IntegerField(unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sap_code',
            field=models.IntegerField(unique=True, verbose_name='Код в системе SAP'),
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='№ Телефона'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='already_get_amount',
            field=models.FloatField(default=0.0, verbose_name='Уже поставлено'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.FloatField(verbose_name='Сумма договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.company', verbose_name='Общество'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.provider', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deliver_penalty_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент пени за просрочку поставки'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_item',
            field=models.CharField(blank=True, max_length=200, verbose_name='Предмет договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='contracts.staff', verbose_name='Куратор договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Договор закрыт'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='max_deliver_penalty_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимум пени за просрочку поставки'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='max_paid_penalty_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимум пени за просрочку поставки'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=16, unique=True, verbose_name='№ Договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='paid_penalty',
            field=models.FloatField(default=0.0, verbose_name='Оплачено пени со стороны КА'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='paid_penalty_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент пени за просрочку поставки'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_term',
            field=models.IntegerField(default=60, null=True, verbose_name='Срок оплаты, дней'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='penalty_for_payment',
            field=models.FloatField(default=0.0, verbose_name='Сумма пени за просрочку оплаты'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='penalty_for_supply',
            field=models.FloatField(default=0.0, verbose_name='Сумма пени за просрочку поставки'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pretension_status',
            field=models.CharField(choices=[('UI', 'Не инициирована'), ('BP', 'Допретензионное направлено'), ('PN', 'Направлена СЗ на претензию'), ('PT', 'Направлена претензия'), ('LN', 'Направлена СЗ по исковому'), ('LS', 'Иск подан в суд'), ('LF', 'Суд завершен'), ('SM', 'Прекращено руководством'), ('FN', 'Завершена')], default='UI', max_length=2, verbose_name='Статус претензионной работы'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='remains_deliver_amount',
            field=models.FloatField(blank=True, verbose_name='Остаток к поставке'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Дата начала договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sum_of_pretensions',
            field=models.FloatField(default=0.0, verbose_name='Суммарная пеня по договору'),
        ),
        migrations.AlterField(
            model_name='deliver',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='deliver',
            name='delivered',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поставки'),
        ),
        migrations.AlterField(
            model_name='deliver',
            name='invoice',
            field=models.CharField(max_length=128, verbose_name='№ Счета-фактуры/УПД'),
        ),
        migrations.AlterField(
            model_name='deliver',
            name='invoice_date',
            field=models.DateField(verbose_name='Дата фактуры/УПД'),
        ),
        migrations.AlterField(
            model_name='deliver',
            name='paid_fact',
            field=models.DateField(blank=True, null=True, verbose_name='Факт оплаты'),
        ),
        migrations.AlterField(
            model_name='deliver',
            name='payment_term',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='deliver',
            name='total',
            field=models.FloatField(verbose_name='Сумма поставки'),
        ),
        migrations.AlterField(
            model_name='department',
            name='cut',
            field=models.CharField(max_length=10, verbose_name='Сокращенное наименование'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=72, verbose_name='Наименование отдела'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='case',
            field=models.CharField(blank=True, max_length=100, verbose_name='№ Дела'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='decision_image',
            field=models.FileField(blank=True, upload_to='lawsuit/decision/%Y/%m/%d/%s', verbose_name='Решение суда (скан)'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='decision_penalty',
            field=models.FloatField(blank=True, verbose_name='Сумма по решению суда'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='is_satisfied',
            field=models.BooleanField(default=False, verbose_name='Признак оплаты КА'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='letter_image',
            field=models.FileField(upload_to='lawsuit/%Y/%m/%d/%s', verbose_name='Исковое (скан)'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='note_date',
            field=models.DateField(verbose_name='Дата искового'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='number',
            field=models.CharField(max_length=10, verbose_name='№ Искового заявления'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='penalty_amount',
            field=models.FloatField(verbose_name='Сумма требований'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='penalty_paid',
            field=models.FloatField(default=0, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='lawsuitnote',
            name='answer_image',
            field=models.FileField(blank=True, upload_to='pretension_note/answers/%Y/%m/%d/%s', verbose_name='Ответ (скан)'),
        ),
        migrations.AlterField(
            model_name='lawsuitnote',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='lawsuitnote',
            name='have_answer',
            field=models.BooleanField(default=False, verbose_name='Признак ответа'),
        ),
        migrations.AlterField(
            model_name='lawsuitnote',
            name='letter_image',
            field=models.FileField(upload_to='pretension_note/%Y/%m/%d/%s', verbose_name='СЗ (скан)'),
        ),
        migrations.AlterField(
            model_name='lawsuitnote',
            name='note_date',
            field=models.DateField(verbose_name='Дата СЗ'),
        ),
        migrations.AlterField(
            model_name='lawsuitnote',
            name='number',
            field=models.CharField(max_length=10, verbose_name='№ СЗ на ГД об инициировании ИР'),
        ),
        migrations.AlterField(
            model_name='lawsuitnote',
            name='penalty_amount',
            field=models.FloatField(verbose_name='Сумма требований'),
        ),
        migrations.AlterField(
            model_name='pretension',
            name='answer_image',
            field=models.FileField(blank=True, upload_to='pretension/answers/%Y/%m/%d/%s', verbose_name='Ответ (скан)'),
        ),
        migrations.AlterField(
            model_name='pretension',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='pretension',
            name='have_answer',
            field=models.BooleanField(default=False, verbose_name='Признак ответа'),
        ),
        migrations.AlterField(
            model_name='pretension',
            name='is_satisfied',
            field=models.BooleanField(default=False, verbose_name='Признак оплаты'),
        ),
        migrations.AlterField(
            model_name='pretension',
            name='letter_image',
            field=models.FileField(upload_to='pretension/%Y/%m/%d/%s', verbose_name='Претензия (скан)'),
        ),
        migrations.AlterField(
            model_name='pretension',
            name='note_date',
            field=models.DateField(verbose_name='Дата претензии'),
        ),
        migrations.AlterField(
            model_name='pretension',
            name='number',
            field=models.CharField(max_length=10, verbose_name='№ Претензии'),
        ),
        migrations.AlterField(
            model_name='pretension',
            name='penalty_amount',
            field=models.FloatField(verbose_name='Сумма требований'),
        ),
        migrations.AlterField(
            model_name='pretension',
            name='penalty_paid',
            field=models.FloatField(default=0, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='pretensionnote',
            name='answer_image',
            field=models.FileField(blank=True, upload_to='pretension_note/answers/%Y/%m/%d/%s', verbose_name='Ответ (скан)'),
        ),
        migrations.AlterField(
            model_name='pretensionnote',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='pretensionnote',
            name='have_answer',
            field=models.BooleanField(default=False, verbose_name='Статус ответа'),
        ),
        migrations.AlterField(
            model_name='pretensionnote',
            name='letter_image',
            field=models.FileField(upload_to='pretension_note/%Y/%m/%d/%s', verbose_name='Служебная записка (скан)'),
        ),
        migrations.AlterField(
            model_name='pretensionnote',
            name='note_date',
            field=models.DateField(verbose_name='Дата СЗ'),
        ),
        migrations.AlterField(
            model_name='pretensionnote',
            name='number',
            field=models.CharField(max_length=10, verbose_name='№ служебки на УПОБ'),
        ),
        migrations.AlterField(
            model_name='pretensionnote',
            name='penalty_amount',
            field=models.FloatField(verbose_name='Сумма требований'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.TextField(verbose_name='Адрес КА'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='cut_name',
            field=models.CharField(max_length=50, verbose_name='Сокращенное наименование'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='e_mail',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта КА'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='inn',
            field=models.IntegerField(unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='payd_penalty',
            field=models.FloatField(default=0.0, verbose_name='Оплаченные Пени'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='penalty_for_payment',
            field=models.FloatField(default=0.0, verbose_name='Пеня за просрочку оплаты'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='penalty_for_supply',
            field=models.FloatField(default=0.0, verbose_name='Пеня за просрочку поставки'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='sap_code',
            field=models.IntegerField(unique=True, verbose_name='Код КА в SAP'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='sum_of_pretensions',
            field=models.FloatField(default=0.0, verbose_name='Сумма выставленных претензий'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='total_penalty',
            field=models.FloatField(default=0.0, verbose_name='Итого пеня'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dep_director',
            field=models.BooleanField(default=False, verbose_name='Статус начальника отдела'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='main_man',
            field=models.BooleanField(default=False, verbose_name='Статус руководителя верхнего звена'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sap_id',
            field=models.IntegerField(unique=True, verbose_name='Код в системе SAP'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
